# Generated by Django 2.0.3 on 2018-07-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('shipping_price', models.FloatField()),
                ('description', models.TextField(max_length=10000)),
            ],
        ),
    ]
